/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseManager;

import Business.Inventory.DeviceMaintenance;
import Business.Inventory.MaintenanceHistory;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class MaintenanceHistoryJPanel extends javax.swing.JPanel {

    JPanel upc;
    DeviceMaintenance dm;

    /**
     * Creates new form MaintenanceHistoryJPanel
     */
    public MaintenanceHistoryJPanel(JPanel upc, DeviceMaintenance dm) {
        initComponents();
        this.upc = upc;
        this.dm = dm;

        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) maintenanceHistoryJTable.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[3];
        for (MaintenanceHistory mh : dm.getMaintenanceHistory()) {
            row[0] = new SimpleDateFormat("MM-dd-yyyy").format(mh.getLastMaintenanceDate());
            row[1] = mh.getMaintenanceNotes();
            row[2] = mh.getMemp().getFirstName() + " " + mh.getMemp().getLastName();

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        maintenanceHistoryJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        maintenanceHistoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Maintenance Date", "Maintenance Procedure Detail", "Done By"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(maintenanceHistoryJTable);
        if (maintenanceHistoryJTable.getColumnModel().getColumnCount() > 0) {
            maintenanceHistoryJTable.getColumnModel().getColumn(0).setResizable(false);
            maintenanceHistoryJTable.getColumnModel().getColumn(1).setResizable(false);
            maintenanceHistoryJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 81, 1033, 423));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Maintenance History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 19, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 522, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable maintenanceHistoryJTable;
    // End of variables declaration//GEN-END:variables
}
