/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseManager;

import Business.Employee.WarehouseManager;
import Business.Inventory.IDevice;
import Business.Inventory.Warehouse;
import Business.InventoryRecords.SurgeryRoom;
import Business.Organization.InventoryOrganization;
import Business.Reservations.DeviceReservation;
import Business.Reservations.RoomReservation;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ReservationsJPanel extends javax.swing.JPanel {

    JPanel upc;
    InventoryOrganization iOrg;
    WarehouseManager manager;

    /**
     * Creates new form ReservationsJPanel
     */
    public ReservationsJPanel(JPanel upc, InventoryOrganization iOrg, WarehouseManager manager) {
        initComponents();
        this.upc = upc;
        this.iOrg = iOrg;
        this.manager = manager;

        populateDeviceReservationTable();
        populateRoomReservationTable();
    }

    public void populateDeviceReservationTable() {
        DefaultTableModel dtm = (DefaultTableModel) deviceReservationsJTable.getModel();
        dtm.setRowCount(0);

        Object[] row = new Object[7];
        Warehouse w = manager.getWarehouse();
        for (IDevice d : w.getListOfDevices().getDeviceList()) {
            if (!d.getReservations().isEmpty()) {
                for (DeviceReservation dr : d.getReservations()) {
                    row[0] = d.getDeviceDetails().getTypeOfDevice();
                    row[1] = d.getInventoryIDNo();
                    row[2] = new SimpleDateFormat("MM-dd-yyyy").format(dr.getReservationDate());
                    row[3] = new SimpleDateFormat("hh:mm").format(dr.getReservedFrom());
                    row[4] = new SimpleDateFormat("hh:mm").format(dr.getReservedTo());
                    row[5] = dr.getReservedBy();
                    row[6] = dr.getHorg().getHospitalName();

                    dtm.addRow(row);
                }

            }
        }

    }

    public void populateRoomReservationTable() {
        DefaultTableModel dtm = (DefaultTableModel) roomsJTable.getModel();
        dtm.setRowCount(0);

        Object[] row = new Object[6];
        for (SurgeryRoom sr : iOrg.getSurgeryRoomDirectory().getRoomList()) {
            if (!sr.getReservations().isEmpty()) {
                for (RoomReservation rr : sr.getReservations()) {
                    row[0] = sr;
                    row[1] = new SimpleDateFormat("MM-dd-yyyy").format(rr.getReservationDate());
                    row[2] = new SimpleDateFormat("hh:mm").format(rr.getReservedFrom());
                    row[3] = new SimpleDateFormat("hh:mm").format(rr.getReservedTo());
                    row[4] = rr.getReservedBy();
                    row[5] = rr.getHorg().getHospitalName();
                    
                    dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        deviceReservationsJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        backjButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        roomsJTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deviceReservationsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Device Type", "InventoryDevice ID", "Date", "Reserved From", "Reserved To", "Booked By", "Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deviceReservationsJTable);
        if (deviceReservationsJTable.getColumnModel().getColumnCount() > 0) {
            deviceReservationsJTable.getColumnModel().getColumn(0).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(1).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(2).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(3).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(4).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(5).setResizable(false);
            deviceReservationsJTable.getColumnModel().getColumn(6).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 990, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Device and Room Reservations");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Reserved Devices:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Room Reservations:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        roomsJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room", "Reservation Date", "Reserved From", "Reserved To", "Booked By", "Hospital"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(roomsJTable);
        if (roomsJTable.getColumnModel().getColumnCount() > 0) {
            roomsJTable.getColumnModel().getColumn(0).setResizable(false);
            roomsJTable.getColumnModel().getColumn(1).setResizable(false);
            roomsJTable.getColumnModel().getColumn(2).setResizable(false);
            roomsJTable.getColumnModel().getColumn(3).setResizable(false);
            roomsJTable.getColumnModel().getColumn(4).setResizable(false);
            roomsJTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 990, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton2;
    private javax.swing.JTable deviceReservationsJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable roomsJTable;
    // End of variables declaration//GEN-END:variables
}
