/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WarehouseManager;

import Business.EcoSystem;
import Business.Employee.WarehouseManager;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class WarehouseManagerWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upc;
    UserAccount ua;
    Organization org;
    EcoSystem business;
    Network network;
    WarehouseManager manager;

    /**
     * Creates new form WarehouseManagerWorkAreaJPanel
     */
    public WarehouseManagerWorkAreaJPanel(JPanel upc, UserAccount ua, WarehouseManager manager, Organization org, Network network, EcoSystem business) {
        initComponents();
        this.upc = upc;
        this.ua = ua;
        this.org = org;
        this.network = network;
        this.business = business;
        this.manager = manager;
        managerNameJLabel.setText(manager.getFirstName() + " " + manager.getLastName());
        warehouseNameJLabel.setText(manager.getWarehouse().getWarehouseName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkInventoryJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        managerNameJLabel = new javax.swing.JLabel();
        warehouseNameJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkInventoryJButton.setText("Check Inventory>>");
        checkInventoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInventoryJButtonActionPerformed(evt);
            }
        });
        add(checkInventoryJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 120, 189, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome, ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 67, -1, -1));

        managerNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        managerNameJLabel.setText("jLabel2");
        add(managerNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 67, 159, -1));

        warehouseNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        warehouseNameJLabel.setText("jLabel2");
        add(warehouseNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 11, 165, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void checkInventoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInventoryJButtonActionPerformed
        CheckInventoryJPanel ci = new CheckInventoryJPanel(upc, network, manager, ua);
        upc.add("checkinventory", ci);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_checkInventoryJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInventoryJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel managerNameJLabel;
    private javax.swing.JLabel warehouseNameJLabel;
    // End of variables declaration//GEN-END:variables
}
