/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.Employee.Supplier;
import Business.Supplier.SDeviceType;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class AddProductJPanel extends javax.swing.JPanel {

    JPanel upc;
    Supplier s;

    /**
     * Creates new form AddProductJPanel
     */
    public AddProductJPanel(JPanel upc, Supplier s) {
        initComponents();
        this.upc = upc;
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeJTextField = new javax.swing.JTextField();
        pPriceJTextField = new javax.swing.JTextField();
        productNameJLabel = new javax.swing.JLabel();
        productPriceJLabel = new javax.swing.JLabel();
        panelTitleJLabel = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        devicedescriptionJTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        maintenanceJTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        maintenancedueJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(typeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 67, 223, -1));
        add(pPriceJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 98, 223, -1));

        productNameJLabel.setText("Device Type");
        add(productNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 70, -1, -1));

        productPriceJLabel.setText("Price per unit");
        add(productPriceJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        panelTitleJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelTitleJLabel.setText("Add New Product Details");
        add(panelTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 327, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        jLabel1.setText("Device Description");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 129, -1, -1));

        jLabel2.setText("Maintenance Description");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 203, -1, -1));

        devicedescriptionJTextArea.setColumns(20);
        devicedescriptionJTextArea.setRows(5);
        jScrollPane1.setViewportView(devicedescriptionJTextArea);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 129, 223, 56));

        maintenanceJTextArea.setColumns(20);
        maintenanceJTextArea.setRows(5);
        jScrollPane2.setViewportView(maintenanceJTextArea);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 203, 223, 63));

        jLabel3.setText("Maintenance Due after every (Enter no. of days):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 287, -1, -1));
        add(maintenancedueJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 284, 223, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

//for(SDeviceType sdt: s.getProductCatalog().getSupplierCatalog()){
//    if(!sdt.getTypeOfDevice().equals(typeJTextField.getText())){
        try {
            String stringPrice = pPriceJTextField.getText();
            if (stringPrice.isEmpty() == false) {
                int price = Integer.parseInt(stringPrice);
                SDeviceType p = s.getProductCatalog().addProduct();
                p.setTypeOfDevice(typeJTextField.getText());
                p.setCost(price);
                p.setDeviceDescription(devicedescriptionJTextArea.getText());
                p.setMaintenanceProcedureDescription(maintenanceJTextArea.getText());
                p.setMaintenanceDueAfter(Integer.parseInt(maintenancedueJTextField.getText()));
                p.setSupplier(s);
            }
            JOptionPane.showMessageDialog(null, "Product added to Catalog.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please enter valid values.");
        }
  //  }
//    else{
//        JOptionPane.showMessageDialog(null, "Product already exists in the catalog.");
//        return;
//
//    }
//}

    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextArea devicedescriptionJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea maintenanceJTextArea;
    private javax.swing.JTextField maintenancedueJTextField;
    private javax.swing.JTextField pPriceJTextField;
    private javax.swing.JLabel panelTitleJLabel;
    private javax.swing.JLabel productNameJLabel;
    private javax.swing.JLabel productPriceJLabel;
    private javax.swing.JTextField typeJTextField;
    // End of variables declaration//GEN-END:variables
}
