/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.EcoSystem;
import Business.Employee.Supplier;
import Business.Enterprise.Enterprise;
import Business.Enterprise.InventoryEnterprise;
import Business.Network.Network;
import Business.Order.MasterOrderCatalog;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.SupplierOrganization;
import Business.RequestQueue.SupplierEnrollmentRequest;

import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class SupplierWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upc;
    Supplier s;
    MasterOrderCatalog moc;
    UserAccount ua;
    EcoSystem business;
    Network network;
    SupplierOrganization supplierOrg;

    /**
     * Creates new form SupplierWorkAreaJPanel
     */
    public SupplierWorkAreaJPanel(JPanel upc, Supplier s, UserAccount ua, SupplierOrganization supplierOrg, Network network, EcoSystem business) {
        initComponents();
        this.upc = upc;
        this.s = s;
        this.ua = ua;
        this.supplierOrg = supplierOrg;
        this.network = network;
        // this.business = business;
        this.moc = network.getMoc();

        enrollStatusJLabel.setText(s.getApprovalStatus());
        if (s.getApprovalStatus().equals("Approve")) {
            enrollJButton.setEnabled(false);
        }

        sFNameJLabel.setText(s.getCompanyName());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageCatalogJButton = new javax.swing.JButton();
        viewPerformanceJButton = new javax.swing.JButton();
        panelTitleJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sFNameJLabel = new javax.swing.JLabel();
        enrollJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        enrollStatusJLabel = new javax.swing.JLabel();
        viewOrdersJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageCatalogJButton.setText("Manage Product Catalog>>");
        manageCatalogJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCatalogJButtonActionPerformed(evt);
            }
        });
        add(manageCatalogJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 124, -1, -1));

        viewPerformanceJButton.setText("View Sales Performance>>");
        viewPerformanceJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerformanceJButtonActionPerformed(evt);
            }
        });
        add(viewPerformanceJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 199, 167, -1));

        panelTitleJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelTitleJLabel.setText("Supplier Work Area");
        add(panelTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome, ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        sFNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sFNameJLabel.setText("jLabel2");
        add(sFNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 220, -1));

        enrollJButton.setText("Request Enrollment>>");
        enrollJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollJButtonActionPerformed(evt);
            }
        });
        add(enrollJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 167, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Enrollment Status:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        enrollStatusJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enrollStatusJLabel.setText("jLabel3");
        add(enrollStatusJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, -1, -1));

        viewOrdersJButton.setText("View Orders>>");
        viewOrdersJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersJButtonActionPerformed(evt);
            }
        });
        add(viewOrdersJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 167, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageCatalogJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCatalogJButtonActionPerformed
        // TODO add your handling code here:
        ManageProductCatalogJPanel mpcjp = new ManageProductCatalogJPanel(upc, s);
        upc.add("manageProductCatalog", mpcjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageCatalogJButtonActionPerformed

    private void viewPerformanceJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPerformanceJButtonActionPerformed
        // TODO add your handling code here:
        SalesOverviewJPanel sojp = new SalesOverviewJPanel(upc, s, moc);
        upc.add("salesOverview", sojp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_viewPerformanceJButtonActionPerformed

    private void enrollJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollJButtonActionPerformed
        // TODO add your handling code here:
        SupplierEnrollmentRequest sRequest = new SupplierEnrollmentRequest();
        sRequest.setSupplier((Supplier) ua.getEmployee());
        sRequest.setSender(ua);
        sRequest.setMessage("Request For Approval.");
        sRequest.setStatus("Approval awaited.");

        OrganizationDirectory inventoryOrgDirectory = null;
        Organization adminOrg = null;

        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof InventoryEnterprise) {
                inventoryOrgDirectory = e.getOrganizationDirectory();
                for (Organization org : inventoryOrgDirectory.getOrganizationList()) {
                    if (org instanceof AdminOrganization) {
                        adminOrg = org;
                        break;
                    }

                }
            }
        }

        if (adminOrg != null) {
            adminOrg.getRequestQueue().getWorkRequestList().add(sRequest);
            enrollJButton.setEnabled(false);

        }

    }//GEN-LAST:event_enrollJButtonActionPerformed

    private void viewOrdersJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersJButtonActionPerformed
        ViewOrdersJPanel vojp = new ViewOrdersJPanel(upc, supplierOrg);
        upc.add("vieworders", vojp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_viewOrdersJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enrollJButton;
    private javax.swing.JLabel enrollStatusJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageCatalogJButton;
    private javax.swing.JLabel panelTitleJLabel;
    private javax.swing.JLabel sFNameJLabel;
    private javax.swing.JButton viewOrdersJButton;
    private javax.swing.JButton viewPerformanceJButton;
    // End of variables declaration//GEN-END:variables
}
