/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Supplier;

import Business.Order.Order;
import Business.Order.OrderItem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ViewOrderDetailsJPanel extends javax.swing.JPanel {

    JPanel upc;
    Order o;

    /**
     * Creates new form ViewOrderDetailsJPanel
     */
    public ViewOrderDetailsJPanel(JPanel upc, Order o) {
        initComponents();
        this.upc = upc;
        this.o = o;
        orderIDJLabel.setText(String.valueOf(o.getOrderID()));
        populateTable();
        populateFields();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) orderJTable.getModel();
        dtm.setRowCount(0);

        Object[] row = new Object[3];
        for (OrderItem oi : o.getListOfItemsOrdered()) {
            row[0] = oi.getProduct();
            row[1] = oi.getQuantity();
            row[2] = oi.getProduct().getCost() * oi.getQuantity();

            dtm.addRow(row);
        }
    }

    public void populateFields() {
        warehouseJLabel.setText(o.getWarehouse().getWarehouseName());
        addressJLabel.setText(o.getWarehouse().getAddress());
        accountNameJLabel.setText(o.getPaymentDetails().getAccountName());
        accountNoJLabel.setText(String.valueOf(o.getPaymentDetails().getAccountNo()));
        routingNoJLabel.setText(o.getPaymentDetails().getRoutingNo());
        bankNameJLabel.setText(o.getPaymentDetails().getBankName());
        totalAmountJLabel.setText(String.valueOf(o.getTotalamount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        orderIDJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        warehouseJLabel = new javax.swing.JLabel();
        accountNoJLabel = new javax.swing.JLabel();
        routingNoJLabel = new javax.swing.JLabel();
        accountNameJLabel = new javax.swing.JLabel();
        bankNameJLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addressJLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalAmountJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Order ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        orderIDJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        orderIDJLabel.setText("jLabel1");
        add(orderIDJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 514, -1, -1));

        orderJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product", "Quantity", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 610, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Order Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Warehouse:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Payment Details:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Account Number");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Account Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Routing Number");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Bank Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        warehouseJLabel.setText("jLabel9");
        add(warehouseJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, -1));

        accountNoJLabel.setText("jLabel10");
        add(accountNoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 350, -1));

        routingNoJLabel.setText("jLabel11");
        add(routingNoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 350, -1));

        accountNameJLabel.setText("jLabel12");
        add(accountNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 350, -1));

        bankNameJLabel.setText("jLabel13");
        add(bankNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Address:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        addressJLabel.setText("jLabel11");
        add(addressJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 430, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Total Amount:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, -1, -1));

        totalAmountJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalAmountJLabel.setText("jLabel11");
        add(totalAmountJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNameJLabel;
    private javax.swing.JLabel accountNoJLabel;
    private javax.swing.JLabel addressJLabel;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel bankNameJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel orderIDJLabel;
    private javax.swing.JTable orderJTable;
    private javax.swing.JLabel routingNoJLabel;
    private javax.swing.JLabel totalAmountJLabel;
    private javax.swing.JLabel warehouseJLabel;
    // End of variables declaration//GEN-END:variables
}
