/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Employee.Supplier;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class AddSJPanel extends javax.swing.JPanel {

    JPanel upc;
    SupplierEnterprise supplierEnt;
    SupplierOrganization nso;
    Network network;

    /**
     * Creates new form AddSJPanel
     */
    public AddSJPanel(JPanel upc, Network network) {
        initComponents();
        this.upc = upc;
        this.network = network;

        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof SupplierEnterprise) {
                supplierEnt = (SupplierEnterprise) e;

            }
        }
        Organization newSupplierOrg = supplierEnt.getOrganizationDirectory().createOrganization(Organization.Type.Supplier);
        nso = (SupplierOrganization) newSupplierOrg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameJTextField = new javax.swing.JTextField();
        firstNameJLabel = new javax.swing.JLabel();
        addSJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        panelTitleJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameJTextField = new javax.swing.JTextField();
        companyNameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        contactJTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(firstNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 240, -1));

        firstNameJLabel.setText("First Name:");
        add(firstNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        addSJButton.setText("Add Supplier");
        addSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSJButtonActionPerformed(evt);
            }
        });
        add(addSJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        panelTitleJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panelTitleJLabel.setText("Add New Supplier");
        add(panelTitleJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setText("Last Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setText("Company Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        add(lastNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 240, -1));
        add(companyNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 240, -1));

        jLabel3.setText("Address:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel4.setText("Contact No.:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 240, -1));
        add(contactJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSJButtonActionPerformed

        boolean isPresent = false;
        try {
            String firstName = firstNameJTextField.getText();
            String lastName = lastNameJTextField.getText();
            String companyName = companyNameJTextField.getText();
            long contact = Long.parseLong(contactJTextField.getText());
            String address = addressJTextField.getText();

            if (firstName.equals("") || lastName.equals("") || companyName.equals("") || address.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter all details.");
                return;
            }
           

            if (isPresent == false) {
                Supplier supplier = new Supplier();
                supplier.setFirstName(firstName);
                supplier.setLastName(lastName);
                supplier.setCompanyName(companyName);

                nso.setS(supplier);
                nso.getEmployeeDirectory().getEmployeeList().add(supplier);
                JOptionPane.showMessageDialog(null, "Supplier added.");
            } else {
                JOptionPane.showMessageDialog(null, "Supplier already exists");
                return;
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Information.");
            return;
        }


    }//GEN-LAST:event_addSJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField companyNameJTextField;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JLabel panelTitleJLabel;
    // End of variables declaration//GEN-END:variables
}
