/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.MaintenanceOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Organization.SupplierOrganization;
import Business.Role.Role;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class AddUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form AddUserAccount
     */
    private JPanel upc;
    private Network network;
    private OrganizationDirectory od;
    private UserAccountDirectory uad;

    public AddUserAccount(JPanel upc, Network network) {
        initComponents();
        this.network = network;
        this.upc = upc;

        populateEntComboBox();
    }

    public void populateEntComboBox() {
        entJComboBox.removeAllItems();
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            entJComboBox.addItem(e);
        }

    }

    public void populateOrganizationComboBox(Enterprise ent) {
        if (ent != null) {
            if (ent.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital)) {
                populateHospitalOrgComboBox(ent);
            }
            if (ent.getEnterpriseType().equals(Enterprise.EnterpriseType.Supplier)) {
                populateSupplierOrgComboBox(ent);
            }
            if (ent.getEnterpriseType().equals(Enterprise.EnterpriseType.Inventory)) {
                populateInventoryOrgComboBox(ent);
            }
        }

    }

    public void populateHospitalOrgComboBox(Enterprise e) {
        organizationJComboBox.removeAllItems();

        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
            HospitalOrganization horg = (HospitalOrganization) org;
            organizationJComboBox.addItem(horg);
        }
    }

    public void populateSupplierOrgComboBox(Enterprise e) {
        organizationJComboBox.removeAllItems();

        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
            SupplierOrganization sorg = (SupplierOrganization) org;
            organizationJComboBox.addItem(sorg);
        }
    }

    public void populateInventoryOrgComboBox(Enterprise e) {
        organizationJComboBox.removeAllItems();

        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof InventoryOrganization) {
                InventoryOrganization iorg = (InventoryOrganization) org;
                organizationJComboBox.addItem(org);
            } else if (org instanceof MaintenanceOrganization) {
                MaintenanceOrganization morg = (MaintenanceOrganization) org;
                organizationJComboBox.addItem(morg);
            }
        }
    }

    public void populateRoleComboBox(Organization org) {
        for (Role role : org.getSupportedRole()) {
            roleJComboBox.addItem(role);
        }
    }

    public void populateEmployeeComboBox(Organization org) {
        employeeJComboBox.removeAllItems();
        //  for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
        // for(Organization org: e.getOrganizationDirectory().getOrganizationList()){
        for (Employee emp : org.getEmployeeDirectory().getEmployeeList()) {
            employeeJComboBox.addItem(emp);
        }
        //}
        //}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        inactiveJRadioButton = new javax.swing.JRadioButton();
        activeJRadioButton = new javax.swing.JRadioButton();
        employeeJComboBox = new javax.swing.JComboBox();
        roleJComboBox = new javax.swing.JComboBox();
        organizationJComboBox = new javax.swing.JComboBox();
        passwordJTextField = new javax.swing.JPasswordField();
        usernameJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entJComboBox = new javax.swing.JComboBox();
        backJButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Add User Account");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Organization");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Employee");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Role");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Status");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 23));

        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 665, -1, -1));

        addJButton.setText("Add User Account");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 400, 150, 30));

        buttonGroup1.add(inactiveJRadioButton);
        inactiveJRadioButton.setText("Inactive");
        add(inactiveJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        buttonGroup1.add(activeJRadioButton);
        activeJRadioButton.setText("Active");
        add(activeJRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 65, -1));

        add(employeeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 250, -1));

        roleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJComboBoxActionPerformed(evt);
            }
        });
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 250, -1));

        organizationJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationJComboBoxActionPerformed(evt);
            }
        });
        add(organizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 250, -1));
        add(passwordJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));
        add(usernameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 129, 250, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Enterprise");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        entJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entJComboBoxActionPerformed(evt);
            }
        });
        add(entJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 91, 250, -1));

        backJButton1.setText("<<Back");
        backJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButton1ActionPerformed(evt);
            }
        });
        add(backJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 509, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        try {
            String userName = usernameJTextField.getText();
            String password = String.valueOf(passwordJTextField.getPassword());
            boolean check = false;
            if (userName.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(null, "Please enter all details.");
                return;

            }

            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                    check = org.getUserAccountDirectory().checkIfUsernameIsUnique(userName);
                }
            }

            if (check == true) {
                Employee emp = (Employee) employeeJComboBox.getSelectedItem();
                Organization org = (Organization) organizationJComboBox.getSelectedItem();
                Role role = (Role) roleJComboBox.getSelectedItem();
                if (org != null) {
                    if (!activeJRadioButton.isSelected()) {
                        org.getUserAccountDirectory().createUserAccount(userName, password, emp, role, network, "Disable");

                    } else {
                        org.getUserAccountDirectory().createUserAccount(userName, password, emp, role, network, "Active");

                    }

                }
            }

            JOptionPane.showMessageDialog(null, "User Account added.");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Information.");
            return;
        }

    }//GEN-LAST:event_addJButtonActionPerformed

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed

    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void organizationJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationJComboBoxActionPerformed

        roleJComboBox.removeAllItems();
        Organization org = (Organization) organizationJComboBox.getSelectedItem();
        if (org != null) {
            populateRoleComboBox(org);
            populateEmployeeComboBox(org);
        }
    }//GEN-LAST:event_organizationJComboBoxActionPerformed

    private void entJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entJComboBoxActionPerformed
        Enterprise ent = (Enterprise) entJComboBox.getSelectedItem();
        populateOrganizationComboBox(ent);


    }//GEN-LAST:event_entJComboBoxActionPerformed

    private void backJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButton1ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeJRadioButton;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton backJButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox employeeJComboBox;
    private javax.swing.JComboBox entJComboBox;
    private javax.swing.JRadioButton inactiveJRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox organizationJComboBox;
    private javax.swing.JPasswordField passwordJTextField;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTextField usernameJTextField;
    // End of variables declaration//GEN-END:variables
}
