/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Enterprise.InventoryEnterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Inventory.WarehouseDirectory;
import Business.Network.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.RequestQueue.Request;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel upc;
    Enterprise enterprise;
    Network network;
    EmployeeDirectory supplierDirectory;
    EmployeeDirectory wManagerDirectory;
    WarehouseDirectory warehouseDirectory;
    SupplierOrganization supplierOrganization;
    SupplierEnterprise supplierEnterprise;
    InventoryEnterprise iEnt;
    UserAccount adminAccount;
    AdminOrganization aorg;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel upc, Network network, UserAccount account) {
        initComponents();
        this.upc = upc;
        this.network = network;
        this.adminAccount = account;
        checkSupplierRequests();
        networkNameJLabel.setText(network.getName());
        adminNameJLabel.setText(account.getEmployee().getFirstName() + " " + account.getEmployee().getLastName());
    }

    public void checkSupplierRequests() {
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof InventoryEnterprise) {
                for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof AdminOrganization) {
                        this.aorg = (AdminOrganization) organization;
                    }
                }
            }
        }

        for (Request req : aorg.getRequestQueue().getWorkRequestList()) {
            if (req.getStatus().equals("Approval awaited.")) {
                JOptionPane.showMessageDialog(null, "There are Supplier Enrollment Requests pending.");
            }
            return;
        }
    }

    public InventoryEnterprise getInventoryEnterprise(Network network) {
        EnterpriseDirectory ed = network.getEnterpriseDirectory();
        for (Enterprise e : ed.getEnterpriseList()) {
            if (e instanceof InventoryEnterprise) {

                iEnt = (InventoryEnterprise) e;
                break;
            }
        }
        return iEnt;
    }

    public void getSupplierOrganization() {
        EnterpriseDirectory ed = network.getEnterpriseDirectory();

        for (Enterprise e : ed.getEnterpriseList()) {
            if (e.getEnterpriseType().equals(Enterprise.EnterpriseType.Supplier)) {
                supplierEnterprise = (SupplierEnterprise) e;
                for (Organization sorg : e.getOrganizationDirectory().getOrganizationList()) {
                    if (sorg.getType().equals(Organization.Type.Supplier)) {
                        supplierOrganization = (SupplierOrganization) sorg;
                    }
                }

            }
        }
    }

    public void getWarehouseManagersList() {
        EnterpriseDirectory ed = network.getEnterpriseDirectory();
        for (Enterprise e : ed.getEnterpriseList()) {
            if (e instanceof InventoryEnterprise) {
                for (Organization worg : e.getOrganizationDirectory().getOrganizationList()) {
                    if (worg instanceof InventoryOrganization) {
                        wManagerDirectory = worg.getEmployeeDirectory();
                    }
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        networkNameJLabel = new javax.swing.JLabel();
        manageSupplierJButton = new javax.swing.JButton();
        manageWarehouseJButton = new javax.swing.JButton();
        manageUserAccJButton = new javax.swing.JButton();
        manageHospitalsJButton = new javax.swing.JButton();
        orderJButton = new javax.swing.JButton();
        mangeSurgeriesJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        adminNameJLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inventoryUsageJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Admin Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 11, -1, -1));

        networkNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        networkNameJLabel.setText("jLabel2");
        add(networkNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        manageSupplierJButton.setText("Manage Suppliers>>");
        manageSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSupplierJButtonActionPerformed(evt);
            }
        });
        add(manageSupplierJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 188, -1));

        manageWarehouseJButton.setText("Manage Warehouses>>");
        manageWarehouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehouseJButtonActionPerformed(evt);
            }
        });
        add(manageWarehouseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 188, -1));

        manageUserAccJButton.setText("Manage User Accounts>>");
        manageUserAccJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccJButtonActionPerformed(evt);
            }
        });
        add(manageUserAccJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 188, -1));

        manageHospitalsJButton.setText("Manage Hospitals>>");
        manageHospitalsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHospitalsJButtonActionPerformed(evt);
            }
        });
        add(manageHospitalsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 188, -1));

        orderJButton.setText("Order Devices>>");
        orderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJButtonActionPerformed(evt);
            }
        });
        add(orderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 188, -1));

        mangeSurgeriesJButton.setText("Manage Surgery Procedures>>");
        mangeSurgeriesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mangeSurgeriesJButtonActionPerformed(evt);
            }
        });
        add(mangeSurgeriesJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 188, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Welcome, ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        adminNameJLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adminNameJLabel.setText("jLabel3");
        add(adminNameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Network:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        inventoryUsageJButton.setBackground(new java.awt.Color(51, 51, 51));
        inventoryUsageJButton.setForeground(new java.awt.Color(255, 255, 255));
        inventoryUsageJButton.setText("View Inventory Usage>>");
        inventoryUsageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryUsageJButtonActionPerformed(evt);
            }
        });
        add(inventoryUsageJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSupplierJButtonActionPerformed
        ManageSuppliersJPanel ms = new ManageSuppliersJPanel(upc, network, adminAccount);
        upc.add("managesupplier", ms);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageSupplierJButtonActionPerformed

    private void manageUserAccJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccJButtonActionPerformed
        ManageUserAccountJPanel ms = new ManageUserAccountJPanel(upc, network);
        upc.add("manageuseraccount", ms);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageUserAccJButtonActionPerformed

    private void manageHospitalsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHospitalsJButtonActionPerformed
        ManageHospitalsJPanel mh = new ManageHospitalsJPanel(upc, network);
        upc.add("managehospitals", mh);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageHospitalsJButtonActionPerformed

    private void manageWarehouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehouseJButtonActionPerformed
        ManageWarehousesJPanel mw = new ManageWarehousesJPanel(upc, getInventoryEnterprise(network));
        upc.add("managewarehouse", mw);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageWarehouseJButtonActionPerformed

    private void orderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJButtonActionPerformed
        OrderDevicesJPanel od = new OrderDevicesJPanel(upc, network, adminAccount);
        upc.add("orderdevices", od);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_orderJButtonActionPerformed

    private void mangeSurgeriesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mangeSurgeriesJButtonActionPerformed
        ManageSurgeryProceduresJPanel msd = new ManageSurgeryProceduresJPanel(upc, network);
        upc.add("managesurgerydevices", msd);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_mangeSurgeriesJButtonActionPerformed

    private void inventoryUsageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryUsageJButtonActionPerformed
        InventoryUsageJPanel iujp = new InventoryUsageJPanel(upc, getInventoryEnterprise(network));
        upc.add("inventoryusagejpanel", iujp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_inventoryUsageJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminNameJLabel;
    private javax.swing.JButton inventoryUsageJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageHospitalsJButton;
    private javax.swing.JButton manageSupplierJButton;
    private javax.swing.JButton manageUserAccJButton;
    private javax.swing.JButton manageWarehouseJButton;
    private javax.swing.JButton mangeSurgeriesJButton;
    private javax.swing.JLabel networkNameJLabel;
    private javax.swing.JButton orderJButton;
    // End of variables declaration//GEN-END:variables
}
