/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Enterprise.InventoryEnterprise;
import Business.Inventory.Warehouse;
import Business.Inventory.WarehouseDirectory;
import Business.Organization.InventoryOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ManageWarehousesJPanel extends javax.swing.JPanel {

    JPanel upc;
    InventoryEnterprise inventoryEnterprise;
    InventoryOrganization iorg;
    WarehouseDirectory wd;

    /**
     * Creates new form ManageWarehouseManagersJPanel
     */
    public ManageWarehousesJPanel(JPanel upc, InventoryEnterprise inventoryEnterprise) {
        initComponents();
        this.upc = upc;
        this.inventoryEnterprise = inventoryEnterprise;
        populateWarehouseTable();

    }

    public void populateWarehouseTable() {
        DefaultTableModel dtm = (DefaultTableModel) warehouseJTable.getModel();
        dtm.setRowCount(0);
        for (Organization org : inventoryEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof InventoryOrganization) {
                iorg = (InventoryOrganization) org;
                break;
            }
        }
        Object[] row = new Object[3];
        wd = iorg.getWarehouseDirectory();
        for (Warehouse w : wd.getWarehouseList()) {
            row[0] = w;
            row[1] = w.getAddress();
            row[2] = w.getId();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        newWarehouseNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        addJButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        warehouseJTable = new javax.swing.JTable();
        removeJButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        manageWarehouseJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Warehouses");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 25, -1, -1));
        add(newWarehouseNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 220, -1));

        jLabel2.setText("Enter Warehouse Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Add New Warehouse to your network:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 255, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, -1, -1));

        addJButton.setText("Add Warehouse");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        warehouseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Warehouse Name", "Address", "Warehouse ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(warehouseJTable);
        if (warehouseJTable.getColumnModel().getColumnCount() > 0) {
            warehouseJTable.getColumnModel().getColumn(0).setResizable(false);
            warehouseJTable.getColumnModel().getColumn(1).setResizable(false);
            warehouseJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 85, 640, 89));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, -1, -1));

        jLabel6.setText("Enter Address:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 220, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 770, 11));

        manageWarehouseJButton.setText("Manage Warehouse Employees>>>");
        manageWarehouseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWarehouseJButtonActionPerformed(evt);
            }
        });
        add(manageWarehouseJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        String name = newWarehouseNameJTextField.getText();
        String address = addressJTextField.getText();
        if (!name.equals("") || !name.equals("")) {
            wd.addWarehouse(name, address);
            populateWarehouseTable();
            JOptionPane.showMessageDialog(null, "Warehouse added successfully.");
        } else {
            JOptionPane.showMessageDialog(null, "Please enter valid and complete information.");
            return;
        }
    }//GEN-LAST:event_addJButtonActionPerformed

    private void manageWarehouseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWarehouseJButtonActionPerformed
        int selectedRow = warehouseJTable.getSelectedRow();
       
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        Warehouse warehouse = (Warehouse) warehouseJTable.getValueAt(selectedRow, 0);
        ManageWarehouseEmployeesJPanel mwe = new ManageWarehouseEmployeesJPanel(upc, inventoryEnterprise, warehouse);
        upc.add("managewarehouseemployees", mwe);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageWarehouseJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        int selectedRow = warehouseJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this warehouse?", "Warning", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            Warehouse warehouse = (Warehouse) warehouseJTable.getValueAt(selectedRow, 0);
            wd.removeWarehouse(warehouse);
            populateWarehouseTable();
        }
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        populateWarehouseTable();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton manageWarehouseJButton;
    private javax.swing.JTextField newWarehouseNameJTextField;
    private javax.swing.JButton removeJButton;
    private javax.swing.JTable warehouseJTable;
    // End of variables declaration//GEN-END:variables
}
