
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Employee.CareTeamLeader;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ManageHospitalEmployeesJPanel extends javax.swing.JPanel {

    JPanel upc;
    Network network;
    HospitalEnterprise hospitalEnterprise;

    /**
     * Creates new form ManageHospitalEmployeesJPanel
     */
    public ManageHospitalEmployeesJPanel(JPanel upc, Network network) {
        initComponents();
        this.upc = upc;
        this.network = network;

        populateComboBox1();
        populateComboBox2();
    }

    public void populateComboBox1() {
        hospitalJComboBox1.removeAllItems();
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof HospitalEnterprise) {
                hospitalEnterprise = (HospitalEnterprise) e;
                for (Organization horg : e.getOrganizationDirectory().getOrganizationList()) {
                    HospitalOrganization temphorg = (HospitalOrganization) horg;
                    hospitalJComboBox1.addItem(temphorg);
                }
            }
        }
        populateTable();
    }

    public void populateComboBox2() {
        hospitalJComboBox2.removeAllItems();
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof HospitalEnterprise) {
                hospitalEnterprise = (HospitalEnterprise) e;
                for (Organization horg : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
                    HospitalOrganization temphorg = (HospitalOrganization) horg;
                    hospitalJComboBox2.addItem(temphorg);
                }
            }
        }

    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) employeesJTable.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[4];

        HospitalOrganization temphorg = (HospitalOrganization) hospitalJComboBox1.getSelectedItem();
        for (Employee emp : temphorg.getEmployeeDirectory().getEmployeeList()) {
            row[0] = emp.getId();
            row[1] = emp;
            row[2] = emp.getContactNo();
            row[3] = emp.getAddress();

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnameJTextField = new javax.swing.JTextField();
        lnameJTextField = new javax.swing.JTextField();
        addEmployeeJButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        contactJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hospitalJComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeesJTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        hospitalJComboBox1 = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        refreshJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 155, -1));
        add(lnameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 156, -1));

        addEmployeeJButton.setText("Add Care Team Leader");
        addEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeJButtonActionPerformed(evt);
            }
        });
        add(addEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jLabel9.setText("Enter Employee Address:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 404, -1, -1));

        jLabel10.setText("Enter Contact No.:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 433, -1, -1));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 156, -1));

        jLabel4.setText("Add Employees of a Hospital (Care Team Leaders):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 287, -1, -1));
        add(contactJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 156, -1));

        jLabel5.setText("Select Hospital:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 311, -1, -1));

        add(hospitalJComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 155, -1));

        jLabel7.setText("Enter Employee First Name:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 342, -1, -1));

        jLabel8.setText("Enter Employee Last Name:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, 20));

        employeesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EmployeeID", "Name", "Contact No.", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeesJTable);
        if (employeesJTable.getColumnModel().getColumnCount() > 0) {
            employeesJTable.getColumnModel().getColumn(0).setResizable(false);
            employeesJTable.getColumnModel().getColumn(1).setResizable(false);
            employeesJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 97, 557, 108));

        jLabel6.setText("Select Hospital:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 62, -1, -1));

        hospitalJComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalJComboBox1ActionPerformed(evt);
            }
        });
        add(hospitalJComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 59, 155, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 266, 557, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Hospital Employees");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 223, -1, -1));

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        removeJButton.setText("Remove");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 223, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeJButtonActionPerformed
        try {
            String firstName = fnameJTextField.getText();
            String lastName = lnameJTextField.getText();
            String address = addressJTextField.getText();
            long contact = Long.parseLong(contactJTextField.getText());
            HospitalOrganization horg = (HospitalOrganization) hospitalJComboBox2.getSelectedItem();

            CareTeamLeader emp = new CareTeamLeader();
            emp.setFirstName(firstName);
            emp.setLastName(lastName);
            emp.setAddress(address);
            emp.setContactNo(contact);
            emp.setHospital(horg);
            horg.getEmployeeDirectory().getEmployeeList().add(emp);
            populateTable();
            JOptionPane.showMessageDialog(null, "Care Team Leader has been added.");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please Enter Valid Information.");
            return;
        }
    }//GEN-LAST:event_addEmployeeJButtonActionPerformed

    private void hospitalJComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalJComboBox1ActionPerformed
        populateTable();
    }//GEN-LAST:event_hospitalJComboBox1ActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed
        int selectedRow = (int) employeesJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this employee?", "Warning", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            CareTeamLeader emp = (CareTeamLeader) employeesJTable.getValueAt(selectedRow, 1);
            HospitalOrganization horg = (HospitalOrganization) hospitalJComboBox1.getSelectedItem();
            horg.getEmployeeDirectory().removeEmployee(emp);
            populateTable();
        }
    }//GEN-LAST:event_removeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployeeJButton;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField contactJTextField;
    private javax.swing.JTable employeesJTable;
    private javax.swing.JTextField fnameJTextField;
    private javax.swing.JComboBox hospitalJComboBox1;
    private javax.swing.JComboBox hospitalJComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lnameJTextField;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
}
