
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Enterprise.Enterprise;
import Business.Enterprise.SupplierEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ManageSuppliersJPanel extends javax.swing.JPanel {

    JPanel upc;
    SupplierEnterprise supplierEnt;
    Network network;
    SupplierOrganization supplierOrg;
    UserAccount adminAccount;

    /**
     * Creates new form ManageSuppliersJPanel
     */
    public ManageSuppliersJPanel(JPanel upc, Network network, UserAccount adminAccount) {
        initComponents();
        this.upc = upc;
        this.network = network;
        //this.supplierEnt = supplierEnt;
        //this.supplierOrg = supplierOrg;
        this.adminAccount = adminAccount;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) suppliersJTable.getModel();
        dtm.setRowCount(0);

        Object[] row = new Object[2];
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof SupplierEnterprise) {
                supplierEnt = (SupplierEnterprise) e;
                for (Organization horg : e.getOrganizationDirectory().getOrganizationList()) {
                    SupplierOrganization temphorg = (SupplierOrganization) horg;
                    row[0] = temphorg.getOrganizationID();
                    row[1] = temphorg;

                    dtm.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        suppliersJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        viewSupplierJButton = new javax.swing.JButton();
        backjButton2 = new javax.swing.JButton();
        manageRequestsJButton = new javax.swing.JButton();
        refreshJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        suppliersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Supplier ID", "Supplier"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(suppliersJTable);
        if (suppliersJTable.getColumnModel().getColumnCount() > 0) {
            suppliersJTable.getColumnModel().getColumn(0).setResizable(false);
            suppliersJTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 79, 375, 103));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Suppliers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 27, -1, -1));

        addJButton.setText("Add New Supplier>>");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 211, 175, -1));

        removeJButton.setText("Remove Supplier");
        removeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeJButtonActionPerformed(evt);
            }
        });
        add(removeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 211, -1, -1));

        viewSupplierJButton.setText("View Supplier>>");
        viewSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierJButtonActionPerformed(evt);
            }
        });
        add(viewSupplierJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 252, 113, -1));

        backjButton2.setText("<<Back");
        backjButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButton2ActionPerformed(evt);
            }
        });
        add(backjButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        manageRequestsJButton.setText("Manage Supplier Requests>>");
        manageRequestsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestsJButtonActionPerformed(evt);
            }
        });
        add(manageRequestsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 252, -1, -1));

        refreshJButton.setText("Refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });
        add(refreshJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 79, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        AddSJPanel ajp = new AddSJPanel(upc, network);
        upc.add("AddSupplier", ajp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);

    }//GEN-LAST:event_addJButtonActionPerformed

    private void viewSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierJButtonActionPerformed
        int selectedRow = suppliersJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        SupplierOrganization sorg = (SupplierOrganization) suppliersJTable.getValueAt(selectedRow, 1);

        ViewSJPanel vjp = new ViewSJPanel(upc, sorg.getS());
        upc.add("ViewSupplier", vjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);

    }//GEN-LAST:event_viewSupplierJButtonActionPerformed

    private void removeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeJButtonActionPerformed

        int selectedRow = (int) suppliersJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        int result = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this supplier?", "Warning", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            SupplierOrganization s = (SupplierOrganization) suppliersJTable.getValueAt(selectedRow, 1);
            supplierEnt.getOrganizationDirectory().getOrganizationList().remove(s);
            supplierEnt.getEmployeeDirectory().getEmployeeList().remove(s.getS());
        }
        populateTable();
    }//GEN-LAST:event_removeJButtonActionPerformed

    private void backjButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButton2ActionPerformed
        // TODO add your handling code here:
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backjButton2ActionPerformed

    private void manageRequestsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestsJButtonActionPerformed

        ManageSupplierRequestsJPanel msrjp = new ManageSupplierRequestsJPanel(upc, network, adminAccount);
        upc.add("ManageSupplierRequestsJPanel", msrjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_manageRequestsJButtonActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        populateTable();
    }//GEN-LAST:event_refreshJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backjButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageRequestsJButton;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton removeJButton;
    private javax.swing.JTable suppliersJTable;
    private javax.swing.JButton viewSupplierJButton;
    // End of variables declaration//GEN-END:variables
}
