/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.RequestQueue.SupplierEnrollmentRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class ProcessSupplierRequest extends javax.swing.JPanel {

    JPanel upc;
    SupplierEnrollmentRequest req;

    /**
     * Creates new form ProcessSupplierRequest
     */
    public ProcessSupplierRequest(JPanel upc, SupplierEnrollmentRequest req) {
        initComponents();
        this.upc = upc;
        this.req = req;
        populateComboBox();
    }

    public void populateComboBox() {
        descisionJComboBox.addItem("Approve");
        descisionJComboBox.addItem("Not Approved");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewSupplierJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        descisionJComboBox = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Enter Approval Descision");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        viewSupplierJButton.setText("View Supplier");
        viewSupplierJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSupplierJButtonActionPerformed(evt);
            }
        });
        add(viewSupplierJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        submitJButton.setText("Submit Decision");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        add(submitJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Process Supplier Request");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        add(descisionJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 150, -1));

        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewSupplierJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSupplierJButtonActionPerformed
        ViewSJPanel vs = new ViewSJPanel(upc, req.getSupplier());
        upc.add("viewsupplier", vs);
        CardLayout l = (CardLayout) upc.getLayout();
        l.next(upc);
    }//GEN-LAST:event_viewSupplierJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        String descision = (String) descisionJComboBox.getSelectedItem();
        req.setStatus(descision);
        req.getSupplier().setApprovalStatus(descision);
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox descisionJComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton viewSupplierJButton;
    // End of variables declaration//GEN-END:variables
}
