/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Inventory.IDeviceType;
import Business.InventoryRecords.SurgeryProcedure;
import Business.InventoryRecords.SurgeryRoom;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class ViewSurgeryDetailsJPanel extends javax.swing.JPanel {

    JPanel upc;
    SurgeryProcedure sp;

    /**
     * Creates new form ViewSurgeryDetailsJPanel
     */
    public ViewSurgeryDetailsJPanel(JPanel upc, SurgeryProcedure sp) {
        initComponents();
        this.upc = upc;
        this.sp = sp;
        GridLayout gdlt = new GridLayout(5, 7);
        devicesJPanel.setLayout(gdlt);
        roomsJPanel.setLayout(gdlt);

        populateFields();

    }

    public void populateFields() {
        nameJLabel.setText(sp.getName());
        descriptionJLabel.setText(sp.getDescription());
        for (IDeviceType idt : sp.getDevicesUsed()) {
            JLabel label = new JLabel();
            label.setText(idt.getTypeOfDevice());
            devicesJPanel.add(label);
            label.setVisible(true);
            label.setForeground(Color.CYAN);
            devicesJPanel.revalidate();
            devicesJPanel.repaint();
        }

        for (SurgeryRoom sr : sp.getRoomListForThisSurgery()) {
            JLabel label = new JLabel();
            label.setText(sr.toString());
            roomsJPanel.add(label);
            label.setForeground(Color.CYAN);
            label.setVisible(true);
            roomsJPanel.revalidate();
            roomsJPanel.repaint();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();
        descriptionJLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        devicesJPanel = new javax.swing.JPanel();
        roomsJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Surgery Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Surgery Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Surgery Description:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Devices Required:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Suitable Rooms:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameJLabel.setText("jLabel6");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 240, -1));

        descriptionJLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descriptionJLabel.setText("jLabel7");
        add(descriptionJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 113, 710, 22));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        devicesJPanel.setBackground(new java.awt.Color(255, 255, 255));
        devicesJPanel.setLayout(new java.awt.GridBagLayout());
        add(devicesJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 730, 120));

        roomsJPanel.setBackground(new java.awt.Color(255, 255, 255));
        roomsJPanel.setLayout(new java.awt.GridBagLayout());
        add(roomsJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 720, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel descriptionJLabel;
    private javax.swing.JPanel devicesJPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JPanel roomsJPanel;
    // End of variables declaration//GEN-END:variables
}
