/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminWorkArea;

import Business.Order.MasterOrderCatalog;
import Business.Order.Order;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aastha
 */
public class ViewOrderHistoryJPanel extends javax.swing.JPanel {

    JPanel upc;
    MasterOrderCatalog moc;

    /**
     * Creates new form ViewOrderHistoryJPanel
     */
    public ViewOrderHistoryJPanel(JPanel upc, MasterOrderCatalog moc) {
        initComponents();
        this.upc = upc;
        this.moc = moc;

        populateOrderHistoryTable();
    }

    public void populateOrderHistoryTable() {
        DefaultTableModel dtm = (DefaultTableModel) orderHistoryJTable.getModel();
        dtm.setRowCount(0);
        Object[] row = new Object[3];
        for (Order o : moc.getMoc()) {
            row[0] = o;
            row[1] = o.getSupplier();
            row[2] = o.getTotalamount();

            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderHistoryJTable = new javax.swing.JTable();
        viewOrderBillJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Order History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        orderHistoryJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Supplier", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderHistoryJTable);
        if (orderHistoryJTable.getColumnModel().getColumnCount() > 0) {
            orderHistoryJTable.getColumnModel().getColumn(0).setResizable(false);
            orderHistoryJTable.getColumnModel().getColumn(1).setResizable(false);
            orderHistoryJTable.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 67, -1, 337));

        viewOrderBillJButton.setText("View Order Bill>>");
        viewOrderBillJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrderBillJButtonActionPerformed(evt);
            }
        });
        add(viewOrderBillJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 433, -1, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewOrderBillJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrderBillJButtonActionPerformed
        int selectedRow = orderHistoryJTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row.");
            return;
        }
        Order o = (Order) orderHistoryJTable.getValueAt(selectedRow, 0);
        ViewOrderBillJPanel vodjp = new ViewOrderBillJPanel(upc, o);
        upc.add("ViewOrderItemJPanel", vodjp);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.next(upc);
    }//GEN-LAST:event_viewOrderBillJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        upc.remove(this);
        CardLayout layout = (CardLayout) upc.getLayout();
        layout.previous(upc);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable orderHistoryJTable;
    private javax.swing.JButton viewOrderBillJButton;
    // End of variables declaration//GEN-END:variables
}
