/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CareTeamLeaderWorkArea;


import Business.Employee.CareTeamLeader;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Aastha
 */
public class CareTeamLeaderWorkAreaJPanel extends javax.swing.JPanel {
JPanel upc;
UserAccount ua;
Organization org;
Network network;
CareTeamLeader emp;
    /**
     * Creates new form CareTeamLeaderWorkAreaJPanel
     */
    public CareTeamLeaderWorkAreaJPanel(JPanel upc, UserAccount ua, CareTeamLeader emp, Organization org, Network network) {
        initComponents();
        this.upc=upc;
        this.ua=ua;
        this.org=org;
        this.network=network;
        this.emp=emp;
        
        nameJLabel.setText(ua.getEmployee().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        makeReservationsJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nameJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        makeReservationsJButton.setText("Make Surgery Reservations>>");
        makeReservationsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReservationsJButtonActionPerformed(evt);
            }
        });
        add(makeReservationsJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome, ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        nameJLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameJLabel.setText("jLabel2");
        add(nameJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void makeReservationsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReservationsJButtonActionPerformed
       MakeReservationsJPanel mrjp = new MakeReservationsJPanel(upc, ua, emp,(HospitalOrganization)org, network);
       upc.add("makereservations", mrjp);
       CardLayout layout = (CardLayout)upc.getLayout();
       layout.next(upc);
    }//GEN-LAST:event_makeReservationsJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton makeReservationsJButton;
    private javax.swing.JLabel nameJLabel;
    // End of variables declaration//GEN-END:variables
}
